name       : perl-test-warnings
version    : 0.026
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-0.026.tar.gz : ae2b68b1b5616704598ce07f5118efe42dc4605834453b7b2be14e26f9cc9a08
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test for warnings and the lack of them
description: |
    Test for warnings and the lack of them
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
