name       : perl-test-warnings
version    : '0.31'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-0.031.tar.gz : 1e542909fef305e45563e9878ea1c3b0c7cef1b28bb7ae07eba2e1efabec477b
homepage   : https://metacpan.org/pod/Test::Warnings
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Test::Warnings - Test for warnings and the lack of them
description: |
    This module is intended to be used as a drop-in replacement for Test::NoWarnings: it also adds an extra test, but runs this test before done_testing calculates the test count, rather than after. It does this by hooking into done_testing as well as via an END block. You can declare a plan, or not, and things will still Just Work.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
